version: 1.0.1-build{build}
configuration: Release
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - appveyor-retry dotnet restore -v Minimal
build_script:
- cmd: dotnet build src\AspNetCore.SslRedirect -c %CONFIGURATION%
after_build:
- cmd: dotnet pack src\AspNetCore.SslRedirect -c %CONFIGURATION%
test_script:
- cmd: dotnet test test\AspNetCore.SslRedirect.Tests -c %CONFIGURATION%
artifacts:
- path: src\AspNetCore.SslRedirect\bin\%CONFIGURATION%\*.nupkg
deploy: off